[project]
name = "ai-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.8.1",
    "langchain-groq>=0.3.2",
    "mcp-use>=1.3.1",
    "mcp[cli]>=1.9.4",
]
